### ISSUE TITLE
Module version numbers with decimal points

### ISSUE THREAD

**Issue by rmlockwood** [cdfarrow/FLExTools#1]
I'd like to be able to put version 1.0.1 on my modules, but it seems that only integers are allowed. Is it possible to change this?

**Comment by cdfarrow** [comment]
My philosophy on version numbers is to keep it simple. I don't expect 
FlexTools Modules to turn into complex suites of code needing multiple 
current versions with subversions for bugfixes, etc. As a workmate said 
to me once, "numbers are free." If you get to version 42 quickly because 
you're making lots of changes, is that a problem? I'm interested in your 
thoughts, but would prefer to leave it as-is.

**Comment by cdfarrow** [comment]
Version 1.2.4 (released 10 Nov 2015) allows Version to be a string (or any type that can be cast to a string with str())
