### ISSUE TITLE
Don't show the folder name in the module list

### ISSUE THREAD

**Issue by bbryson** [cdfarrow/flextools#20]
In the list of modules, the ones that are in folders have that folder name prepended to the module name:

FLExTrans.Settings Tool
Lookup.Lookup Settings Tool
FLExTrans.Sense Linker Tool

It gets cumbersome to always include the folder name when telling users which module to use, but just referring to the name is confusing for new users.  Once someone is familiar with the tool, they don't need the folder name.

If they need the folder name for some reason, they can find it with "Module Info".  To me, it doesn't seem like it is needed.

If other developers of FlexTools scripts disagree, then maybe there could be an option to hide it?

**Comment by cdfarrow** [comment]
I put the full path in the UI, thinking of it as a namespace path, so that there could be FlexTrans.Initialise and MyCoolApp.Initialise, too, without them being confused in the UI. I'm not aware of anyone actually using duplicate names, and in this example they could be named FlexTrans.FlexTrans_Initialise, etc. to avoid confusion. I'll go ahead and make the change as you have suggested.

**Comment by cdfarrow** [comment]
@bbryson I see the full module name in the main list and, in the report window when the module is run. We can remove the folder name on these. However, in the collections manager, and any error messages where, say, the module can't be found, I'm thinking it needs to keep the full path, otherwise it might be confusing to know where a module actually comes from. Do you agree, or could that be more confusing having two styles of reference?

**Comment by bbryson** [comment]
I think there are definitely places where you still need the folder name.

I'm ambivalent on the report window--I feel like I don't mind seeing it there.  It was mainly in the list of modules for the user to click on.

In the Collections Manager, I think it is useful to have the full path.  For one thing, anyone dealing with the Collections Manager is already deep enough into the structure of it all to understand that there are folders etc.

See what Ron or Eric think.

**Comment by rmlockwood** [comment]
What you have planned, Craig looks fine to me.

**Comment by cdfarrow** [comment]
The path name has been removed in the main list and in the report window when the module is run. Fixed for v2.1.2
