### ISSUE TITLE
Icon images look worse after Windows 11 22H2 update

### ISSUE THREAD

**Issue by rmlockwood** [cdfarrow/flextools#26]
![image](https://user-images.githubusercontent.com/7088137/203240021-49318fcb-cad0-4896-afe4-16eed888334a.png)

**Comment by cdfarrow** [comment]
Hopefully it is a wider issue that MS will fix in a patch soon...

**Comment by rmlockwood** [comment]
I had someone using FLExTools and FLExTrans during the post-EMDC track and their icons also looked bad.

**Comment by rmlockwood** [comment]
These continue to be ugly.
![image](https://github.com/cdfarrow/flextools/assets/7088137/bc8050d6-4368-4843-8dc4-17434cbc60b8)

**Comment by cdfarrow** [comment]
It turned out to be a bit-depth issue, where the 32-bit icons were being displayed as 8-bit (the default) in Windows 22H2. My guess is that it was a bug/accidental that it was working previously.
Fixed in cdfutils v1.0.6 and the next version of flextoolslib. (Use InstallOrUpdate.vbs to update the libraries)
